spring:
  application:
    name: "read_replica_impl"

  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/products
      username: root
      password: ritik
      hikari:
        pool-name: PrimaryPool

    replica:
      jdbc-url: jdbc:mysql://localhost:3306/replica
      username: root
      password: ritik
      pool-name: ReplicaPool

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true


